@extends('layouts.app')
@section('title', 'Register Fixed Asset')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-0">Register Fixed Asset</h1><div class="text-muted">Create the asset identity, cost and depreciation profile. Capitalization is posted after review.</div></div><a href="{{ route('fixed-assets.index') }}" class="btn btn-outline-secondary">Back</a></div>
<form method="POST" action="{{ route('fixed-assets.store') }}">@csrf
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Asset Identification</div><div class="card-body"><div class="row g-3"><div class="col-md-6"><label class="form-label">Asset name *</label><input name="name" class="form-control" value="{{ old('name') }}" required></div><div class="col-md-3"><label class="form-label">Acquisition date *</label><input type="date" name="acquisition_date" class="form-control" value="{{ old('acquisition_date', now()->toDateString()) }}" required></div><div class="col-md-3"><label class="form-label">In-service date</label><input type="date" name="in_service_date" class="form-control" value="{{ old('in_service_date') }}"></div><div class="col-md-4"><label class="form-label">Vendor</label><select name="vendor_id" class="form-select"><option value="">Select vendor</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}">{{ $vendor->code }} — {{ $vendor->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Item / Service</label><select name="item_id" class="form-select"><option value="">Not linked</option>@foreach($items as $item)<option value="{{ $item->id }}">{{ $item->code }} — {{ $item->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Department</label><select name="department_id" class="form-select"><option value="">Not assigned</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Location</label><input name="location" class="form-control" value="{{ old('location') }}"></div><div class="col-md-6"><label class="form-label">Description</label><input name="description" class="form-control" value="{{ old('description') }}"></div></div></div></div>
<div class="card border-0 shadow-sm mb-3"><div class="card-header bg-white fw-semibold">Capitalization and Depreciation</div><div class="card-body"><div class="row g-3"><div class="col-md-3"><label class="form-label">Cost *</label><input type="number" step="0.0001" min="0.0001" name="cost" class="form-control" required></div><div class="col-md-3"><label class="form-label">Salvage value</label><input type="number" step="0.0001" min="0" name="salvage_value" class="form-control" value="0"></div><div class="col-md-3"><label class="form-label">Useful life (months) *</label><input type="number" min="1" name="useful_life_months" class="form-control" required></div><div class="col-md-3"><label class="form-label">Method</label><input class="form-control" value="Straight-line" disabled></div>@foreach(['asset_account_id' => 'Fixed asset account *', 'accumulated_depreciation_account_id' => 'Accumulated depreciation account *', 'depreciation_expense_account_id' => 'Depreciation expense account *', 'offset_account_id' => 'Capitalization offset account *'] as $field => $label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><select name="{{ $field }}" class="form-select" required><option value="">Select account</option>@foreach($accounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div>@endforeach</div></div></div>
<div class="text-end"><button class="btn btn-primary">Save Asset Draft</button></div></form>
@endsection
